OPTIONS (SKIP=1)
load data
infile 'package.txt'
TRUNCATE INTO TABLE ndc_package
FIELDS TERMINATED BY '\t' 
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
( 
    PRODUCTID,
    PRODUCTNDC,
    NDCPACKAGECODE,
    PACKAGEDESCRIPTION char(500)
)
